<div class="story_views_" id="<?php echo $wo['story']['id']; ?>">

	<div class="story_view_list">

		<div class="user-avatar">

			<img src="<?php echo $wo['story']['avatar'];?>" alt="">

		</div>

		<div class="user-name">

			<span class="user-popover" data-type="user" data-id="<?php echo $wo['story']['user_id']; ?>">

				<a href="<?php echo $wo['story']['url'];?>"><?php echo $wo['story']['name'];?></a>friends_list.phtml
				<span class="label label-danger"><?php echo WoUserTypename($wo['story']['custom_utype']); ?></span>
			</span>

		</div>

	</div>

	<div class="clear"></div>

</div>