<?php
$userAddress = Wo_userAddress($wo['addressId']);
?>

<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol wo-create-forms">
			<h3 class="wo_create_form_cover group">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-grid">
					<rect x="3" y="3" width="7" height="7"></rect>
					<rect x="14" y="3" width="7" height="7"></rect>
					<rect x="14" y="14" width="7" height="7"></rect>
					<rect x="3" y="14" width="7" height="7"></rect>
				</svg>
				Update Address
				<span class="<?php echo Wo_RightToLeft('pull-right'); ?>">
					<a data-ajax="?link1=addressbook" href="<?php echo Wo_SeoLink('index.php?link1=addressbook'); ?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left">
							<polyline points="15 18 9 12 15 6"></polyline>
						</svg><?php echo $wo['lang']['my_addressbook']; ?>
					</a>
				</span>
				<div class="clear"></div>
			</h3>
			<div class="wo_settings_page">
				<form class="address-book-form form-horizontal" method="post">
					<div class="setting-panel row">
						<!-- Text input-->
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="name">Name *</label>
							<div class="col-md-12">
								<input name="name" id="name" type="text" class="form-control input-md" value="<?php if(isset($userAddress['name']) && $userAddress['name'] !=null)  { echo $userAddress['name']; } ?>" required>
							</div>
						</div>
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="company">Company</label>
							<div class="col-md-12 input-group">
								<input id="company" name="company" type="text" class="form-control input-md" value="<?php if(isset($userAddress['company']) && $userAddress['company'] !=null)  { echo $userAddress['company']; } ?>">
							</div>
						</div>
						<div class="form-group col-lg-6">
							<label class="col-md-12" for="phone_number">Phone *</label>
							<div class="col-md-12">
								<input id="phone_number" name="phone_number" type="text" class="form-control input-md" value="<?php if(isset($userAddress['phone_number']) && $userAddress['phone_number'] !=null) { echo $userAddress['phone_number']; } ?>" required>
							</div>
						</div>
						<div class="form-group col-lg-6">
							<label class="col-md-12" for="email">Email</label>
							<div class="col-md-12">
								<input id="email" name="email" type="text" class="form-control input-md" value="<?php if(isset($userAddress['email']) && $userAddress['email'] !=null)  { echo $userAddress['email']; } ?>">
							</div>
						</div>
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="about"><?php echo $wo['lang']['about']; ?></label>
							<div class="col-md-12">
								<textarea name="about" id="about" rows="3" class="form-control input-md"><?php if(isset($userAddress['about']) && $userAddress['about'] != null){ echo $userAddress['about']; } ?></textarea>
							</div>
						</div>
					</div>
					<div class="app-general-alert setting-update-alert"></div>
					<div class="form-group last-sett-btn modal-footer">
						<div class="ball-pulse">
							<div></div>
							<div></div>
							<div></div>
						</div>
						<input id="addressId" name="addressId" type="hidden" class="form-control input-md" value="<?php if(isset($userAddress['id']) && $userAddress['id'] !=null)  { echo $userAddress['id']; } ?>">
						<button type="submit" class="btn btn-main setting-panel-mdbtn">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
								<line x1="12" y1="5" x2="12" y2="19"></line>
								<line x1="5" y1="12" x2="19" y2="12"></line>
							</svg>
							<?php echo $wo['lang']['update']; ?>
						</button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content'); ?>
	</div>
	<!-- .row -->
</div>
<!-- .page-margin -->
<script type="text/javascript">
	$(function() {
		$('form.address-book-form').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=edit_address_book',
			beforeSend: function() {
				$('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
			},
			success: function(data) {
				scrollToTop();
				//console.log(data);
				if (data.status == 200) {
					window.location.href = data.location;
				} else {
					//var errors = data.errors.join("<br>");
					var errors = data.message;
					$('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
					$('.alert-danger').fadeIn(300);
				}
				$('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
			}
		});
	});
</script>