Hi there,

<br><br>

You have received an invitation request from your colleague <a style="color:<?php echo $wo['config']['btn_background_color'];?>" href="<?php echo $wo['user']['url']?>"><?php echo $wo['user']['name'];?></a> to join our social network community <a style="color:<?php echo $wo['config']['btn_background_color'];?>" href="<?php echo $wo['config']['site_url']?>"><?php echo $wo['config']['siteName']?></a>.<br><br>

<br><br>

<?php echo $wo['config']['siteName']?> Team.

<br>

Best regards.