<div class="page_list row boosted_pages note-list-item note-list-item_<?php echo $wo['notepad']['id']; ?>">
  <div class="col-xs-12 col-md-12">
    <div class="page_info">
      <ul>
        <li>
          <div class="col-xs-6 col-md-6 no-padding-left">
            <!-- <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users">
              <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
              <circle cx="9" cy="7" r="4"></circle>
              <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
              <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
            </svg> -->
             <a class="btn-notpad-title" href="<?php echo Wo_SeoLink('index.php?link1=edit-note-pad&npid=' . $wo['notepad']['id']); ?>">
                 <strong><?php echo $wo['notepad']['title']; ?></strong>
                 </a>
          </div>
          <!--<div class="col-xs-12 col-md-10 no-padding-left"> NOTE: <?php // echo substr(nl2br(stripslashes($wo['notepad']['note'])), 0, 150); ?> </div>-->
          <div class="col-xs-12 col-md-2 no-padding-left">
            <div class="book-action-btn">
              <a onclick="return  delete_note(<?php echo $wo['notepad']['id']; ?>)" class="btn btn-danger btn-sm " title=" <?php echo $wo['lang']['delete']; ?>"  title="delete">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
                  <polyline points="3 6 5 6 21 6"></polyline>
                  <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                  <line x1="10" y1="11" x2="10" y2="17"></line>
                  <line x1="14" y1="11" x2="14" y2="17"></line>
                </svg>
              </a>
              <a class="btn btn-main" href="<?php echo Wo_SeoLink('index.php?link1=edit-note-pad&npid=' . $wo['notepad']['id']); ?>" title="edit">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2">
                  <polygon points="16 3 21 8 8 21 3 21 3 16 16 3"></polygon>
                </svg>
              </a>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<script type="text/javascript">
  function delete_note(noteId) {
        if (confirm("Are you sure you want to delete this?") == true) {
            $.ajax({
                url: Wo_Ajax_Requests_File() + '?f=delete_note_pad&noteId=' + noteId,
                beforeSend: function() {
            $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
          },
          success: function(data) {
            scrollToTop();
            //console.log(data);
            if (data.status == 200) {

              $('.note-list-item_'+noteId).remove();
              
              $('.app-general-alert').html('<div class="alert alert-success">The Note is deleted successfully!</div>');
              $('.alert-success').fadeIn(300);

              setTimeout(() => {
                $('.alert-success').fadeOut(300);
              }, 3000);
            } else {
              //var errors = data.errors.join("<br>");
              var errors = data.message;
              $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
              $('.alert-danger').fadeIn(300);
            }
            $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
          }
            });
        }
        else {
            return false;
        }
    }    
</script>