<div class="Restricted-page page-margin">
	<div class="wowonder-well text-center wo_404">
		<img src="<?php echo $wo['config']['theme_url']; ?>/img/R-img.svg">
		<h4>Restricted Page!</h4>
        <h1 class="bold">You Can't Access This Page</h1>
		<p>This page contains premium content that is exclusive to our paid members.</p>
        <p>To access this content and enjoy all the benefits of our membership, please upgrade your plan. <a href="<?php echo Wo_SeoLink('index.php?link1=go-pro'); ?>" data-ajax="?link1=go-pro" class="r-pay-btn">Upgrade Plan</a> </p>
	</div>
</div>